language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

services:
  - postgresql

install: pip install tox tox-travis coveralls psycopg2

script: tox

after_success:
    - coveralls

notifications:
  email: false
