language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

services:
  - postgresql

install: pip install tox tox-travis coveralls psycopg2

before_script:
  - git clone https://github.com/devrimgunduz/pagila.git
  - cd pagila
  - git checkout tags/2.0.1
  - psql -h localhost -p 5432 -U postgres -f pagila-schema.sql
  - psql -h localhost -p 5432 -U postgres -f pagila-data.sql
  - cd ..


script: tox

after_success:
    - coveralls

notifications:
  email: false
